<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRy0m2m5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRy0m2m5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRy0m2m5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRy0m2m5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRy0m2m5\appDevDebugProjectContainer([
    'container.build_hash' => 'Ry0m2m5',
    'container.build_id' => 'a02fa4bd',
    'container.build_time' => 1581072923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRy0m2m5');
